try {
    alert('Начало блока try')
    // code
    //test
    alert('ending of the try')
} catch (err) {
    alert('There is an error in the code')
}